apiVersion: v1
kind: ResourceQuota
metadata:
    name: compute-resources
spec:
    hard:
        requests.cpu: "1"
        requests.memory: "512m"
        requests.ephemeral-storage: "512m"
        limits.cpu: "2"
        limits.memory: "1Gi"
        limits.ephemeral-storage: "1.5Gi"

