kubelet-arg-kube-reserved: "cpu=500m, memory=1G, ephemeral-storage=2Gi"
kubelet-arg=system-reserved: "cpu=500m, memory=1Gi, ephemeral-storage=2Gi"
kubelet-arg=eviction-hard: "memory.available<500Mi,nodefs.available<10%"
